import { resolve } from "node:path"
import { fileURLToPath } from "node:url"
import StyleDictionary from "style-dictionary"
import type { Config, TransformedToken } from "style-dictionary/types"

const __dirname = fileURLToPath(new URL(".", import.meta.url))

// Custom transform: kebab-case with nested path, sanitizing invalid characters
StyleDictionary.registerTransform({
  name: "name/kebab-nested",
  type: "name",
  transform: (token: TransformedToken) => {
    // Replace dots with underscores since CSS variable names can't contain dots
    return token.path.join("-").replace(/\./g, "_")
  },
})

// Custom filter: exclude comment tokens
StyleDictionary.registerFilter({
  name: "exclude-comments",
  filter: (token: TransformedToken) => {
    return !token.path.includes("comment")
  },
})

// Custom format: CSS variables in :root
StyleDictionary.registerFormat({
  name: "css/variables-root",
  format: ({ dictionary }) => {
    const header = `/**
 * Design Tokens - CSS Variables
 * Design System: "Drawing Explorer"
 * Color space: OKLCH for perceptual uniformity
 * Generated by Style Dictionary
 * Do not edit directly
 */

`
    const variables = dictionary.allTokens
      .map((token) => `  --${token.name}: ${token.value};`)
      .join("\n")

    return `${header}:root {\n${variables}\n}\n`
  },
})

// Custom format: Tailwind CSS v4 @theme block
StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) => {
    const header = `/**
 * Design Tokens - Tailwind CSS v4 Theme
 * Design System: "Drawing Explorer"
 * Color space: OKLCH for perceptual uniformity
 * Generated by Style Dictionary
 * Do not edit directly
 */

@import "tailwindcss";

`
    const variables = dictionary.allTokens
      .map((token) => `  --${token.name}: ${token.value};`)
      .join("\n")

    return `${header}@theme {\n${variables}\n}\n`
  },
})

const config: Config = {
  source: [resolve(__dirname, "tokens/**/*.json")],
  platforms: {
    css: {
      transformGroup: "css",
      transforms: ["name/kebab-nested"],
      buildPath: `${resolve(__dirname, "../dist")}/`,
      files: [
        {
          destination: "tokens.css",
          format: "css/variables-root",
          filter: "exclude-comments",
        },
        {
          destination: "tailwind-theme.css",
          format: "css/tailwind-theme",
          filter: "exclude-comments",
        },
      ],
    },
  },
}

async function build() {
  console.log("Building design tokens...")

  const sd = new StyleDictionary(config)
  await sd.buildAllPlatforms()

  console.log("Design tokens built successfully!")
}

build().catch((error) => {
  console.error("Build failed:", error)
  process.exit(1)
})
